create TABLE IF NOT EXISTS Users (
	"name" varchar(30) NOT NULL,
	"login" VARCHAR(30) primary key,
	"password" VARCHAR NOT NULL
);

create table IF NOT EXISTS roles(
	id integer GENERATED by default as IDENTITY primary key,
	role_name VARCHAR(30)
);

create table IF NOT EXISTS user_role(
	login varchar constraint user_role_fk references users, 
	id int CONSTRAINT role_user_fk REFERENCES roles

);



/---insert into users("name",login,"password") VALUES ('TestUser1', 'TestLogin', 'testPassword123');
/---insert into users("name",login,"password") VALUES ('TestUser2', 'TestLogin2', 'testPassword1234');

INSERT into roles(role_name) values('admin');
INSERT into roles(role_name) values('user');
INSERT into roles(role_name) values('operator');

/---insert into user_role(login, id) VALUES ('TestLogin', 1);

